[package]
name = "relay-tendermint"
version = "0.1.0"
edition = "2021"

[dependencies]
prost-types = { version = "0.11", default-features = false }
ibc = { version = "0.29.0", default-features = false, features = ["serde"] }
ibc-proto = { version = "0.26.0", default-features = false, features = ["parity-scale-codec", "borsh"] }
ibc-proto-relayer = { package = "ibc-proto", version = "0.24.1", default-features = false }
ibc-relayer = "0.22.0"
ibc-relayer-types = "0.22.0"
tendermint-rpc = { version = "0.28", default-features = false }
tendermint-light-client-verifier = { version = "0.28", default-features = false }
anyhow = { version = "1.0.56" }
tokio = { version = "1.0" }
lcp-types = { path = "../../types" }
