[package]
name = "ocall-handler"
version = "0.1.0"
edition = "2021"

[dependencies]
sgx_types = { rev = "v1.1.5", git = "https://github.com/apache/incubator-teaclave-sgx-sdk" }
log = { version = "0.4.8" }
flex-error = { version = "0.4.4" }

ocall-commands = { path = "../ocall-commands", default-features = false }
host-environment = { path = "../host-environment" }
store = { path = "../store" }
