[package]
name = "settings"
version = "0.1.0"
edition = "2021"

[dependencies]
sgx_types = { rev = "v1.1.5", git = "https://github.com/apache/incubator-teaclave-sgx-sdk" }

[features]
production = []
