[package]
name = "settings"
version = "0.1.0"
edition = "2021"

[dependencies]
lazy_static = { version = "1.1.0", features = ["spin_no_std"] }

sgx_tstd = { git = "https://github.com/apache/teaclave-sgx-sdk.git", optional = true }

[features]
default = ["std"]
std = []
sgx = ["sgx_tstd"]
