[package]
name = "lcp-types"
version = "0.1.0"
edition = "2021"

[dependencies]
sgx_tstd = { rev = "v1.1.6", git = "https://github.com/apache/incubator-teaclave-sgx-sdk", optional = true }
prost-types = { version = "0.11", default-features = false }
ibc = { version = "0.29.0", default-features = false, features = ["serde"] }
ibc-proto = { version = "0.26.0", default-features = false, features = ["parity-scale-codec", "borsh"] }
tendermint = { version = "0.29", default-features = false }
tendermint-proto = { version = "0.29", default-features = false }
serde = { version = "1.0", default-features = false, features = ["alloc", "derive"] }
serde_json = { version = "1.0", default-features = false, features = ["alloc"] }
flex-error = { version = "0.4.4", default-features = false }

[features]
default = ["std"]
std = []
sgx = [
    "sgx_tstd",
]
