[package]
name = "lcp-types"
version = "0.1.0"
edition = "2021"

[dependencies]
sgx_types = { rev = "v1.1.6", git = "https://github.com/apache/incubator-teaclave-sgx-sdk" }
prost = { version = "0.11", default-features = false }
ibc = { version = "0.29.0", default-features = false, features = ["serde"], optional = true }
lcp-proto = { path = "../../proto", default-features = false }
serde = { version = "1.0.184", default-features = false, features = ["alloc", "derive"] }
serde_with = { version = "2.0.1", default-features = false, features = ["alloc", "macros"] }
serde_json = { version = "1.0", default-features = false, features = ["alloc"] }
flex-error = { version = "0.4.4", default-features = false }
hex = { version = "0.4", default-features = false, features = ["alloc"] }
time = { version = "0.3", default-features = false, features = ["macros", "parsing"] }

[dev-dependencies]
proptest = "1.2.0"
ibc = { version = "0.29.0", default-features = false, features = ["serde"] }

[features]
default = ["std"]
std = [
    "flex-error/std",
    "time/std",
]
ibc = [
    "dep:ibc"
]
