[package]
name = "lcp-ibc-client"
version = "0.1.0"
edition = "2021"

[dependencies]
sgx_tstd = { git = "https://github.com/apache/teaclave-sgx-sdk.git", optional = true }
ibc = {git = "https://github.com/bluele/ibc-rs", branch = "sgx", default-features = false }
ibc-proto = { git = "https://github.com/bluele/ibc-rs", branch = "sgx", default-features = false }
serde = { version = "1.0", default-features = false, features = ["alloc"] }
libsecp256k1 = { version = "0.3.5", optional = true }
libsecp256k1-sgx = { package = "libsecp256k1", rev = "sgx_1.1.3-patch", git = "https://github.com/bluele/libsecp256k1-rs-sgx", optional = true }
context = { path = "../context", default-features = false }
commitments = { path = "../commitments", default-features = false }

[features]
default = ["std"]
std = [
    "context/std",
    "commitments/std"
]
sgx = [
    "sgx_tstd",
    "libsecp256k1-sgx",
    "context/sgx",
    "commitments/sgx"
]
