[package]
name = "attestation-report"
version = "0.1.0"
edition = "2021"

[dependencies]
sgx_tstd = { git = "https://github.com/apache/teaclave-sgx-sdk.git", optional = true }
sgx_types = { git = "https://github.com/apache/teaclave-sgx-sdk.git" }
sgx_trts = { git = "https://github.com/apache/teaclave-sgx-sdk.git" }
rustls_sgx = { package = "rustls", git = "https://github.com/mesalock-linux/rustls", branch = "mesalock_sgx", optional = true }
rustls          = { version = "0.19",   optional = true }
webpki_sgx = { package = "webpki", git = "https://github.com/mesalock-linux/webpki", branch = "mesalock_sgx", optional = true }
webpki          = { version = "0.21",   optional = true }
base64_sgx = { package = "base64", git = "https://github.com/mesalock-linux/rust-base64-sgx", optional = true }
base64 = { git = "https://github.com/marshallpierce/rust-base64", optional = true }
pem_sgx = { package = "pem", version = "0.8.2", git = "https://github.com/mesalock-linux/pem-rs-sgx", optional = true }
pem = { version = "1.0", optional = true }
chrono = { version = "0.4.19", default-features = false, features = ["alloc"]}
serde_json = { version = "1.0", default-features = false, features = ["alloc"] }
log = "0.4.8"

settings = { path = "../settings" }
enclave-utils = { path = "../../enclave-modules/utils", optional = true }

[features]
default = ["std"]
std = [
    "webpki",
    "rustls",
    "base64",
    "pem"
]
sgx = [
    "sgx_tstd",
    "webpki_sgx",
    "rustls_sgx",
    "base64_sgx",
    "pem_sgx",
    "enclave-utils"
]
