[package]
name = "attestation-report"
version = "0.1.0"
edition = "2021"

[dependencies]
sgx_types = { rev = "v1.1.6", git = "https://github.com/apache/incubator-teaclave-sgx-sdk", features = ["extra_traits"] }
tendermint = { version = "0.29", default-features = false }
chrono = { version = "0.4.19", default-features = false, features = ["alloc"]}
serde = { version = "1.0", default-features = false, features = ["alloc"] }
serde_json = { version = "1.0", default-features = false, features = ["alloc"] }
crypto = { path = "../crypto", default-features = false }
lcp-types = { path = "../types", default-features = false }
flex-error = { version = "0.4.4", default-features = false }
base64 = { git = "https://github.com/marshallpierce/rust-base64", default-features = false, features = ["alloc"] }
hex = { version = "0.4", default-features = false, features = ["alloc"] }

pem_sgx = { package = "pem", version = "0.8.2", git = "https://github.com/mesalock-linux/pem-rs-sgx", optional = true }
pem = { version = "1.0", optional = true }
rustls_sgx = { package = "rustls", git = "https://github.com/mesalock-linux/rustls", branch = "mesalock_sgx", optional = true }
rustls     = { version = "0.19", optional = true }
webpki_sgx = { package = "webpki", git = "https://github.com/mesalock-linux/webpki", branch = "mesalock_sgx", optional = true }
webpki     = { version = "0.21", optional = true }

[features]
default = ["std"]
std = [
    "pem",
    "rustls",
    "webpki"
]
sgx = [
    "pem_sgx",
    "rustls_sgx",
    "webpki_sgx"
]
