[package]
name = "tendermint"
version = "0.1.0"
edition = "2021"

[dependencies]
sgx_tstd = { git = "https://github.com/apache/teaclave-sgx-sdk.git", optional = true }
ibc = { git = "https://github.com/bluele/ibc-rs", branch = "sgx", default-features = false }
ibc-proto = { git = "https://github.com/bluele/ibc-rs", branch = "sgx", default-features = false }
tendermint-light-client-verifier = { git = "https://github.com/informalsystems/tendermint-rs", rev = "235480171081fed74de7b3d3c19911304df29831", default-features = false }
tendermint-proto = { git = "https://github.com/informalsystems/tendermint-rs", rev = "235480171081fed74de7b3d3c19911304df29831", default-features = false }
prost = { version = "0.9", default-features = false }
prost-types = { version = "0.9", default-features = false }
sha2 = { version = "0.8", default-features = false }
time = { version = "0.3", default-features = false }
lazy_static = { version = "1.1.0", features = ["spin_no_std"] }
serde = { version = "1.0", default-features = false, features = ["alloc"] }
serde_json = { version = "1.0", default-features = false, features = ["alloc"] }

log = { version = "0.4.8", optional = true }
log-sgx = { package = "log", git = "https://github.com/mesalock-linux/log-sgx", optional = true }
anyhow = { version = "1.0.56", optional = true }
anyhow-sgx = { package = "anyhow", rev = "sgx_1.1.3", git = "https://github.com/mesalock-linux/anyhow-sgx.git", optional = true }
thiserror = { version = "1.0.30", optional = true }
thiserror-sgx = { package = "thiserror", git = "https://github.com/mesalock-linux/thiserror-sgx.git", optional = true }

light-client = { path = "../light-client", default-features = false }
commitments = { path = "../commitments", default-features = false, features = ["sgx"] }
validation-context = { path = "../validation-context", default-features = false, features = ["sgx"] }

[features]
default = ["std"]
std = [
    "log",
    "anyhow",
    "thiserror",
    "commitments/std",
    "light-client/std"
]
sgx = [
    "sgx_tstd",
    "log-sgx",
    "anyhow-sgx",
    "thiserror-sgx",
    "commitments/sgx",
    "light-client/sgx"
]
