[package]
name = "lcp-client"
version = "0.1.0"
edition = "2021"

[dependencies]
ibc-proto = { version = "0.26.0", default-features = false }
prost = { version = "0.11", default-features = false }
prost-types = { version = "0.11", default-features = false }
serde = { version = "1.0", default-features = false, features = ["alloc", "derive"] }
flex-error = { version = "0.4.4", default-features = false }

attestation-report = { path = "../attestation-report", default-features = false }
light-client = { path = "../light-client", default-features = false }
lcp-proto = { path = "../../proto", default-features = false }
crypto = { path = "../crypto", default-features = false }

[dev-dependencies]
sgx_types = { rev = "v1.1.6", git = "https://github.com/apache/incubator-teaclave-sgx-sdk", features = ["extra_traits"] }
ibc = { version = "0.29.0", default-features = false, features = ["serde", "std"] }
chrono = { version = "0.4", default-features = false, features = ["alloc", "clock"]}
base64 = { git = "https://github.com/marshallpierce/rust-base64", default-features = false, features = ["alloc"] }

mock-lc = { path = "../mock-lc" }
store = { path = "../store" }
context = { path = "../context" }
crypto = { path = "../crypto", default-features = false, features = ["std"] }

[features]
default = ["std"]
std = [
    "flex-error/std",
    "light-client/std",
    "attestation-report/std",
]
