[package]
name = "store"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0", default-features = false, features = ["alloc", "derive"] }
serde_json = { version = "1.0", default-features = false, features = ["alloc"] }
sha2 = { version = "0.8", default-features = false }
log = { version = "0.4.8", default-features = false }
flex-error = { version = "0.4.4", default-features = false }
ouroboros = { version = "0.15.5", optional = true }
rocksdb = { version = "0.19.0", optional = true }

[dev-dependencies]
tempdir = "0.3.7"
env_logger = "0.9.0"

[features]
default = ["std"]
std = []
rocksdbstore = [
    "std",
    "rocksdb",
    "ouroboros"
]
