[package]
name = "store"
version = "0.1.0"
edition = "2021"

[dependencies]
sgx_tstd = { git = "https://github.com/apache/teaclave-sgx-sdk.git", optional = true }
serde = { version = "1.0", default-features = false, features = ["alloc", "derive"] }
serde_json = { version = "1.0", default-features = false, features = ["alloc"] }
sha2 = { version = "0.8", default-features = false }
log = { version = "0.4.8", default-features = false }
flex-error = { version = "0.4.4", default-features = false }

[features]
default = ["std"]
std = []
sgx = [
    "sgx_tstd"
]
