[package]
name = "store"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0", default-features = false, features = ["alloc", "derive"] }
log = { version = "0.4.8", default-features = false }
flex-error = { version = "0.4.4", default-features = false }
ouroboros = { version = "0.17.0", optional = true }
rocksdb = { version = "0.21.0", optional = true }

[dev-dependencies]
tempfile = "3"
env_logger = "0.9.0"

[features]
default = ["std"]
std = []
rocksdbstore = [
    "std",
    "rocksdb",
    "ouroboros"
]
