[package]
name = "nodes-runner"
version = "0.1.0"
edition = "2021"

[dependencies]
ibc-relayer = { version = "0.22.0", default-features = false }
ibc-test-framework = { version = "0.22.0", default-features = false }
