[package]
name = "light-client"
version = "0.1.0"
edition = "2021"

[dependencies]
prost = { version = "0.11", default-features = false }
prost-types = { version = "0.11", default-features = false }
flex-error = { version = "0.4.4", default-features = false }
serde = { version = "1.0", default-features = false, features = ["alloc"] }
derive_more = { version = "0.99.0", default-features = false }
bincode = { version = "2.0.0-rc.2", default-features = false, features = ["serde", "alloc"] }

lcp-types = { path = "../types", default-features = false }
commitments = { path = "../commitments", default-features = false }
store = { path = "../store", default-features = false }
