[package]
name = "light-client"
version = "0.1.0"
edition = "2021"

[dependencies]
prost = { version = "0.10", default-features = false }
prost-types = { version = "0.10", default-features = false }
ibc = { git = "https://github.com/informalsystems/ibc-rs", rev = "e8c98d440949abf971ac45a68ed9dd9e6e9f48ed", default-features = false }
ibc-proto = { git = "https://github.com/informalsystems/ibc-rs", rev = "e8c98d440949abf971ac45a68ed9dd9e6e9f48ed", default-features = false }
flex-error = { version = "0.4.4", default-features = false }

lcp-types = { path = "../types", default-features = false }
commitments = { path = "../commitments", default-features = false }
