[package]
name = "light-client-registry"
version = "0.1.0"
edition = "2021"

[dependencies]
sgx_tstd = { rev = "v1.1.6", git = "https://github.com/apache/incubator-teaclave-sgx-sdk", optional = true }
flex-error = { version = "0.4.4", default-features = false }

light-client = { path = "../light-client", default-features = false }

[features]
default = ["std"]
std = []
sgx = ["sgx_tstd"]
