[package]
name = "validation-context"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0", default-features = false, features = ["alloc"] }
tendermint-light-client-verifier = { version = "=0.23.7", default-features = false }
rlp = { version = "0.5.1", default-features = false }
lcp-types = { path = "../types", default-features = false }
