[package]
name = "host"
version = "0.1.0"
edition = "2021"

[dependencies]
sgx_urts = { git = "https://github.com/apache/teaclave-sgx-sdk.git" }
sgx_types = { git = "https://github.com/apache/teaclave-sgx-sdk.git" }
log = "0.4.8"
once_cell = "1.15.0"

ocall-handler = { path = "../ocall-handler" }
