[package]
name = "host"
version = "0.1.0"
edition = "2021"

[dependencies]
sgx_urts = { git = "https://github.com/apache/teaclave-sgx-sdk.git" }
sgx_types = { git = "https://github.com/apache/teaclave-sgx-sdk.git" }
log = "0.4.8"
bincode = { version = "1.3" }

ocall-handler = { path = "../../modules/ocall-handler" }
ocall-commands = { path = "../../modules/ocall-commands" }
