[package]
name = "ocall-commands"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0.184", default-features = false, features = ["alloc", "derive"] }
store = { path = "../store", default-features = false }
