[package]
name = "remote-attestation"
version = "0.1.0"
edition = "2021"

[dependencies]
sgx_types = { rev = "v1.1.6", git = "https://github.com/apache/incubator-teaclave-sgx-sdk" }
log = "0.4.8"
rand = "0.8"
hex = { version = "0.4", default-features = false, features = ["alloc"] }
base64 = { git = "https://github.com/marshallpierce/rust-base64", default-features = false, features = ["alloc"] }
httparse = { version = "1.3", default-features = false }
rustls = "0.19"
webpki = "0.21"
webpki-roots = "0.17"
flex-error = { version = "0.4.4" }
sha2 = { version = "0.10.6" }
rsa = { version = "0.9.2", features = ["pem"] }
chrono = { version = "0.4.38", features = ["now"] }

lcp-types = { path = "../types" }
crypto = { path = "../crypto", default-features = false }
attestation-report = { path = "../attestation-report" }
ecall-commands = { path = "../ecall-commands" }
enclave-api = { path = "../enclave-api" }
store = { path = "../store", features = ["rocksdbstore"] }
