[package]
name = "store-rocksdb"
version = "0.1.0"
edition = "2021"

[dependencies]
rocksdb = { version = "0.19.0" }
ouroboros = "0.15.5"

store = { path = "../store" }

[dev-dependencies]
tempdir = "0.3.7"
