[package]
name = "enclave-api"
version = "0.1.0"
edition = "2021"

[dependencies]
sgx_types = { git = "https://github.com/apache/teaclave-sgx-sdk.git" }
sgx_urts = { git = "https://github.com/apache/teaclave-sgx-sdk.git" }
ibc = {git = "https://github.com/bluele/ibc-rs", branch = "sgx", default-features = false }
prost = { version = "0.9", default-features = false }
prost-types = { version = "0.9", default-features = false }
bincode = "1.3"
anyhow = { version = "1.0.56" }
thiserror = { version = "1.0.30" }
log = "0.4.8"

enclave-commands = { path = "../enclave-commands" }
