[package]
name = "enclave-api"
version = "0.1.0"
edition = "2021"

[dependencies]
sgx_types = { git = "https://github.com/apache/teaclave-sgx-sdk.git" }
sgx_urts = { git = "https://github.com/apache/teaclave-sgx-sdk.git" }
ibc = { git = "https://github.com/informalsystems/ibc-rs", rev = "e8c98d440949abf971ac45a68ed9dd9e6e9f48ed", default-features = false }
prost = { version = "0.10", default-features = false }
prost-types = { version = "0.10", default-features = false }
bincode = "1.3"
log = "0.4.8"
flex-error = { version = "0.4.4" }

lcp-types = { path = "../types" }
ecall-commands = { path = "../ecall-commands", features = ["std"] }
lcp-proto = { path = "../../proto", features = ["server"] }
host = { path = "../host" }
