[package]
name = "keymanager"
version = "0.1.0"
edition = "2021"

[dependencies]
flex-error = { version = "0.4.4", default-features = false }

crypto = { path = "../crypto", default-features = false }
