[package]
name = "commitments"
version = "0.1.0"
edition = "2021"

[dependencies]
sgx_types = { git = "https://github.com/apache/teaclave-sgx-sdk.git" }
sgx_trts = { git = "https://github.com/apache/teaclave-sgx-sdk.git" }
serde = { version = "1.0", default-features = false, features = ["alloc"] }
serde_json = { version = "1.0", default-features = false, features = ["alloc"] }
prost = { version = "0.10", default-features = false }
prost-types = { version = "0.10", default-features = false }
ibc = { git = "https://github.com/informalsystems/ibc-rs", rev = "e8c98d440949abf971ac45a68ed9dd9e6e9f48ed", default-features = false }
ibc-proto = { git = "https://github.com/informalsystems/ibc-rs", rev = "e8c98d440949abf971ac45a68ed9dd9e6e9f48ed", default-features = false }
log = { version = "0.4.8", default-features = false }
hex = { version = "0.4", default-features = false, features = ["alloc"] }
sha2 = { version = "0.8", default-features = false }
store = { path = "../store", default-features = false }
rlp = { version = "0.5.1", default-features = false }
flex-error = { version = "0.4.4", default-features = false }

lcp-types = { path = "../types", default-features = false }
validation-context = { path = "../validation-context", default-features = false }
crypto = { path = "../crypto", default-features = false }

[dev-dependencies]
rand = { version = "0.8" }
lcp-types = { path = "../types", default-features = false, features = ["std"] }
