[package]
name = "mock-lc"
version = "0.1.0"
edition = "2021"

[dependencies]
ibc = { version = "0.29.0", default-features = false, features = ["serde", "mocks-no-std"] }
ibc-proto = { version = "0.26.0", default-features = false, features = ["parity-scale-codec", "borsh"] }
serde = { version = "1.0", default-features = false, features = ["alloc"] }
flex-error = { version = "0.4.4", default-features = false }

lcp-types = { path = "../types", default-features = false }
light-client = { path = "../light-client", default-features = false, features = ["ibc"] }
