[package]
name = "mock-lc"
version = "0.1.0"
edition = "2021"

[dependencies]
ibc = { version = "0.29.0", default-features = false, features = ["serde", "mocks-no-std"] }
serde = { version = "1.0.184", default-features = false, features = ["alloc"] }
flex-error = { version = "0.4.4", default-features = false }

lcp-proto = { path = "../../proto", default-features = false }
lcp-types = { path = "../types", default-features = false }
light-client = { path = "../light-client", default-features = false, features = ["ibc"] }
