[package]
name = "tendermint-lc"
version = "0.1.0"
edition = "2021"

[dependencies]
ibc = { version = "0.29.0", default-features = false, features = ["serde"] }
ibc-proto = { version = "0.26.0", default-features = false, features = ["parity-scale-codec", "borsh"] }
tendermint-light-client-verifier = { version = "0.29", default-features = false }
tendermint-proto = { version = "0.29", default-features = false }
prost = { version = "0.11", default-features = false }
prost-types = { version = "0.11", default-features = false }
sha2 = { version = "0.10.6", default-features = false }
time = { version = "0.3", default-features = false }
serde = { version = "1.0", default-features = false, features = ["alloc"] }
log = { version = "0.4.8", default-features = false }
flex-error = { version = "0.4.4", default-features = false }

lcp-types = { path = "../types", default-features = false }
light-client = { path = "../light-client", default-features = false, features = ["ibc"] }
light-client-registry = { path = "../light-client-registry", default-features = false }
commitments = { path = "../commitments", default-features = false }
validation-context = { path = "../validation-context", default-features = false }
crypto = { path = "../crypto", default-features = false }
