[package]
name = "tendermint-lc"
version = "0.1.0"
edition = "2021"

[dependencies]
ibc = { version = "0.29.0", default-features = false, features = ["serde"] }
ibc-proto = { version = "0.26.0", default-features = false }
serde = { version = "1.0", default-features = false, features = ["alloc"] }
log = { version = "0.4.8", default-features = false }
flex-error = { version = "0.4.4", default-features = false }

light-client = { path = "../light-client", default-features = false, features = ["ibc"] }
crypto = { path = "../crypto", default-features = false }

[features]
default = []
std = [
    "flex-error/std",
    "light-client/std",
    "crypto/std"
]
