[package]
name = "cgen"
version = "0.1.0"
edition = "2021"
build = "build.rs"

[dependencies]
ibc = { version = "0.29.0", default-features = false, features = ["serde", "std"] }
ibc-proto = { version = "0.26.0", default-features = false, features = ["parity-scale-codec", "borsh"] }
ibc-test-framework = { version = "0.22.0", default-features = false }
clap = { version = "3.2", features = ["derive"] }
tempdir = "0.3.7"
anyhow = { version = "1.0.56" }
tokio = { version = "1.0" }
log = "0.4.8"
serde = { version = "1.0", default-features = false, features = ["alloc"] }
serde_json = { version = "1.0", default-features = false, features = ["alloc"] }
base64 = { git = "https://github.com/marshallpierce/rust-base64", default-features = false, features = ["alloc"] }
rlp = { version = "0.5.1", default-features = false }

lcp-types = { path = "../../modules/types" }
host = { path = "../../modules/host" }
host-environment = { path = "../../modules/host-environment" }
store = { path = "../../modules/store" }
commitments = { path = "../../modules/commitments" }
enclave-api = { path = "../../modules/enclave-api" }
ecall-commands = { path = "../../modules/ecall-commands" }
attestation-report = { path = "../../modules/attestation-report" }
relay-tendermint = { path = "../../modules/relay/tendermint" }

[features]
default = []
sgx-sw = [
    "enclave-api/sgx-sw",
    "ecall-commands/sgx-sw"
]
