[package]
name = "crypto"
version = "0.1.0"
edition = "2021"

[dependencies]
sgx_types = { git = "https://github.com/apache/teaclave-sgx-sdk.git" }
sgx_tstd = { git = "https://github.com/apache/teaclave-sgx-sdk.git", optional = true }
sgx_trts = { git = "https://github.com/apache/teaclave-sgx-sdk.git", optional = true }
sgx_rand = { git = "https://github.com/apache/teaclave-sgx-sdk.git", optional = true }
rand = { version = "0.8", default-features = false, optional = true }
tiny-keccak = "1.4"
serde = { version = "1.0", default-features = false, features = ["alloc", "derive"] }
hex = { version = "0.4", default-features = false, features = ["alloc"] }
log = { version = "0.4.8", default-features = false }
flex-error = { version = "0.4.4", default-features = false }

secp256k1-non-sgx = { package = "libsecp256k1", version = "0.3.5", default-features = false }
secp256k1-sgx = { package = "libsecp256k1", rev = "sgx_1.1.3-patch", git = "https://github.com/bluele/libsecp256k1-rs-sgx", optional = true }

settings = { path = "../settings", default-features = false }

[features]
default = ["std"]
std = [
    "rand/default",
    "secp256k1-non-sgx/default"
]
sgx = [
    "sgx_tstd",
    "sgx_trts",
    "sgx_rand",
    "secp256k1-sgx",
]
