[package]
name = "service"
version = "0.1.0"
edition = "2021"

[dependencies]
ibc = { version = "0.29.0", default-features = false, features = ["serde"] }
tonic = { version = "0.8", default-features = false }
tonic-reflection = { version = "0.6.0" }
tokio = { version = "1.0", features = ["full"] }
log = "0.4.8"
anyhow = { version = "1.0.56" }
serde_json = { version = "1.0", default-features = false, features = ["alloc"] }

host = { path = "../host" }
enclave-api = { path = "../enclave-api" }
lcp-proto = { path = "../../proto", default-features = false }
attestation-report = { path = "../attestation-report" }
settings = { path = "../settings" }
store = { path = "../store", features = ["rocksdbstore"] }
