[package]
name = "service"
version = "0.1.0"
edition = "2021"

[dependencies]
tonic = { version = "0.8", default-features = false }
tonic-reflection = { version = "0.6.0" }
tokio = { version = "1.0", features = ["full"] }
anyhow = { version = "1.0.56" }
serde_json = { version = "1.0", default-features = false, features = ["alloc"] }

enclave-api = { path = "../enclave-api" }
lcp-proto = { path = "../../proto", default-features = false }
attestation-report = { path = "../attestation-report" }
store = { path = "../store", features = ["rocksdbstore"] }

[features]
sgx-sw = [
    "enclave-api/sgx-sw"
]
